### ISSUE TITLE
How can I upgrade the node-RED version in Bluemix ?

### ISSUE THREAD

**Issue by ty4tw** [node-red/node-red-bluemix#5]
I add the node-red-node-msgpack into node_module by means of chaning package.json and deploy.
now I can see the module were installed from the dashboard of Bluemix.
but, msgpack dosen't work. this happend before when I using the old version of the node-RED.
so, I'm douting the latest version is not deploied by Bluemix.
How can I upgrade the node-RED version in Bluemix ?

and, How can I change the setting.js in Bluemix ?

**Comment by dceejay** [comment]
The default Node-RED page at {yourprojectname}.mybluemix.net has instructions on how to either use IBM DevOps Services or local version with Cloud Foundry (CF) tools. Either allow you to edit the settings.js and then re-commit and push the files back, whereupon the application will be restarted.

On re-deploy the Node-RED application will pull the latest stable version of Node-RED (currently 0.9.1 as I type).

Please use the Google group for general help and discussions. Thanks

**Comment by knolleary** [comment]
Just one minor thing to highlight, which is described in the docs Dave
pointed at: it uses `bluemix-settings.js` rather than `settings.js`.
