### ISSUE TITLE
Renaming the app causes the app to crash at startup

### ISSUE THREAD

**Issue by lmosca** [node-red/node-red-bluemix#6]
If you rename the app, you get a "No cloudant service found" error at app startup.
This is due to the nodeRed application code making an assumption that the Cloudant servicename will always contain the name of the original application name. So, if the app name changes, it means that the nodeRED application fails as it attempts to find Cloudant service.
The problem seems to be in the following lines of the bluemix-settings.js file:
settings.couchAppname = VCAP_APPLICATION['application_name'];
var storageServiceName = process.env.NODE_RED_STORAGE_NAME || new RegExp("^"+settings.couchAppname+".cloudantNoSQLDB");
var couchService = appEnv.getService(storageServiceName);

**Comment by knolleary** [comment]
Hi,

The solution is in that same bit of code. If you rename the app, you must create an environment variable called NODE_RED_STORAGE_NAME set to the name of the cloudant instance it should be using.

Nick
